export const designLink = {
  icons: {
    arrowIcon: {
      up: "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=45-9710&t=HmPcOM7UDIkPFZY9-4",
      down: "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=45-9706&t=HmPcOM7UDIkPFZY9-4",
      left: "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=60-9455&t=HmPcOM7UDIkPFZY9-4",
      right:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=60-9359&t=HmPcOM7UDIkPFZY9-4",
    },
  },
  buttons: {
    basicButton: {
      defaultSmall:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12741&t=EL3Y7dqNrWIWPvmu-4",
      defaultSmallWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12745&t=EL3Y7dqNrWIWPvmu-4",
      defaultSmallWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12749&t=EL3Y7dqNrWIWPvmu-4",
      defaultSmallOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11636&t=EL3Y7dqNrWIWPvmu-4",
      defaultNormal:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12717&t=EL3Y7dqNrWIWPvmu-4",
      defaultNormalWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12721&t=EL3Y7dqNrWIWPvmu-4",
      defaultNormalWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12725&t=EL3Y7dqNrWIWPvmu-4",
      defaultNormalOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11640&t=EL3Y7dqNrWIWPvmu-4",
      defaultMedium:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12729&t=EL3Y7dqNrWIWPvmu-4",
      defaultMediumWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12733&t=EL3Y7dqNrWIWPvmu-4",
      defaultMediumWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12737&t=EL3Y7dqNrWIWPvmu-4",
      defaultMediumOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11697&t=EL3Y7dqNrWIWPvmu-4",
      defaultBig:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12705&t=EL3Y7dqNrWIWPvmu-4",
      defaultBigWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12709&t=EL3Y7dqNrWIWPvmu-4",
      defaultBigWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12713&t=EL3Y7dqNrWIWPvmu-4",
      defaultBigOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11644&t=EL3Y7dqNrWIWPvmu-4",
      primarySmall:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12675&t=wae2h8cpeWjiN2cq-4",
      primarySmallWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12679&t=wae2h8cpeWjiN2cq-4",
      primarySmallWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12683&t=wae2h8cpeWjiN2cq-4",
      primarySmallOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11562&t=EL3Y7dqNrWIWPvmu-4",
      primaryNormal:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12651&t=wae2h8cpeWjiN2cq-4",
      primaryNormalWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12655&t=wae2h8cpeWjiN2cq-4",
      primaryNormalWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12659&t=wae2h8cpeWjiN2cq-4",
      primaryNormalOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11576&t=EL3Y7dqNrWIWPvmu-4",
      primaryMedium:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12663&t=wae2h8cpeWjiN2cq-4",
      primaryMediumWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12667&t=wae2h8cpeWjiN2cq-4",
      primaryMediumWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12671&t=wae2h8cpeWjiN2cq-4",
      primaryMediumOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11671&t=EL3Y7dqNrWIWPvmu-4",
      primaryBig:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12621&t=wae2h8cpeWjiN2cq-4",
      primaryBigWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12625&t=wae2h8cpeWjiN2cq-4",
      primaryBigWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12629&t=wae2h8cpeWjiN2cq-4",
      primaryBigOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11588&t=EL3Y7dqNrWIWPvmu-4",
      secondarySmall:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12639&t=wae2h8cpeWjiN2cq-4",
      secondarySmallWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12643&t=wae2h8cpeWjiN2cq-4",
      secondarySmallWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12647&t=wae2h8cpeWjiN2cq-4",
      secondarySmallOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11600&t=EL3Y7dqNrWIWPvmu-4",
      secondaryNormal:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12584&t=wae2h8cpeWjiN2cq-4",
      secondaryNormalWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12588&t=wae2h8cpeWjiN2cq-4",
      secondaryNormalWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12592&t=wae2h8cpeWjiN2cq-4",
      secondaryNormalOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11604&t=EL3Y7dqNrWIWPvmu-4",
      secondaryMedium:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12596&t=wae2h8cpeWjiN2cq-4",
      secondaryMediumWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12600&t=wae2h8cpeWjiN2cq-4",
      secondaryMediumWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12604&t=wae2h8cpeWjiN2cq-4",
      secondaryMediumOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11685&t=EL3Y7dqNrWIWPvmu-4",
      secondaryBig:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12608&t=wae2h8cpeWjiN2cq-4",
      secondaryBigWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12612&t=wae2h8cpeWjiN2cq-4",
      secondaryBigWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12616&t=wae2h8cpeWjiN2cq-4",
      secondaryBigOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11608&t=EL3Y7dqNrWIWPvmu-4",
      disabledSmall:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12696&t=wae2h8cpeWjiN2cq-4",
      disabledSmallWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12698&t=wae2h8cpeWjiN2cq-4",
      disabledSmallWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12700&t=wae2h8cpeWjiN2cq-4",
      disabledSmallOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11624&t=EL3Y7dqNrWIWPvmu-4",
      disabledNormal:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12684&t=wae2h8cpeWjiN2cq-4",
      disabledNormalWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12686&t=wae2h8cpeWjiN2cq-4",
      disabledNormalWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12688&t=wae2h8cpeWjiN2cq-4",
      disabledNormalOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11626&t=EL3Y7dqNrWIWPvmu-4",
      disabledMedium:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12690&t=wae2h8cpeWjiN2cq-4",
      disabledMediumWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12692&t=wae2h8cpeWjiN2cq-4",
      disabledMediumWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12694&t=wae2h8cpeWjiN2cq-4",
      disabledMediumOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11693&t=EL3Y7dqNrWIWPvmu-4",
      disabledBig:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12630&t=wae2h8cpeWjiN2cq-4",
      disabledBigWithIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12632&t=wae2h8cpeWjiN2cq-4",
      disabledBigWithIconReverse:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=8-12634&t=wae2h8cpeWjiN2cq-4",
      disabledBigOnlyIcon:
        "https://www.figma.com/file/8OFb5MbFJaMxxch3lVx1nd/Grawiki-Design-System-UI-KIT?type=design&node-id=163-11628&t=EL3Y7dqNrWIWPvmu-4",
    },
  },
};
