export const iconsConfig = [
  { name: "BankIcon" },
  { name: "BankIcon", props: { fill: true }, tag: "BankIcon fill" },
  { name: "ToysIcon" },
  { name: "ToysIcon", props: { fill: true }, tag: "ToysIcon fill" },
  { name: "GovernmentIcon" },
  { name: "GovernmentIcon", props: { fill: true }, tag: "GovernmentIcon fill" },
  { name: "HealthIcon" },
  { name: "HealthIcon", props: { fill: true }, tag: "HealthIcon fill" },
  { name: "ControlIcon" },
  { name: "ControlIcon", props: { fill: true }, tag: "ControlIcon fill" },
  { name: "BotIcon" },
  { name: "BotIcon", props: { fill: true }, tag: "BotIcon fill" },
  { name: "InterfaceIcon" },
  { name: "InterfaceIcon", props: { fill: true }, tag: "InterfaceIcon fill" },
  { name: "CloseIcon" },
  { name: "CloseIcon", props: { fill: true }, tag: "CloseIcon fill" },
  { name: "SettingIcon" },
  { name: "SettingIcon", props: { fill: true }, tag: "SettingIcon fill" },
  { name: "AvatarIcon" },
  { name: "AvatarIcon", props: { fill: true }, tag: "AvatarIcon fill" },
  { name: "CreateIcon" },
  { name: "CreateMoreIcon" },
  { name: "EditStateIcon" },
  { name: "EyeIcon" },
  { name: "TrashIcon" },
  { name: "FindIcon" },
  { name: "NewWindowIcon" },
  { name: "PasswordEyeIcon" },
  {
    name: "PasswordEyeIcon",
    props: { hidden: true },
    tag: "PasswordEyeIcon hidden",
  },
  { name: "MenuIcon" },

  { name: "ArrowIcon", props: { direction: "down" }, tag: "ArrowIcon down" },
  { name: "ArrowIcon", props: { direction: "up" }, tag: "ArrowIcon up" },
  { name: "ArrowIcon", props: { direction: "left" }, tag: "ArrowIcon left" },
  { name: "ArrowIcon", props: { direction: "right" }, tag: "ArrowIcon right" },

  { name: "GoogleIcon" },
  { name: "NotificationIcon" },
  { name: "NotificationIcon", props: { fill: true } },
  { name: "Notification3DIcon" },
  { name: "Notification3DIcon", props: { fill: true } },
  { name: "HelpIcon" },
  { name: "IndentIcon" },
  { name: "ItalicIcon" },
  { name: "BoldIcon" },
  { name: "OrderedListIcon" },
  { name: "OutdentIcon" },
  { name: "StrikeIcon" },
  { name: "SubscriptIcon" },
  { name: "SuperscriptIcon" },
  { name: "UnderlineIcon" },
  { name: "UnorderedListIcon" },
  { name: "PencilIcon" },
  { name: "Pencil3DIcon" },
  { name: "Writing3DIcon" },
  { name: "Clapping3DIcon" },
  { name: "ClappingIcon" },
  { name: "Pinched3DIcon" },
  { name: "PinchedIcon" },
  { name: "ThumbsDown3DIcon" },
  { name: "ThumbsDownIcon" },
  { name: "ThumbsUp3DIcon" },
  { name: "ThumbsUpIcon" },
  { name: "FacebookIcon" },
  { name: "InstagramIcon" },
  { name: "TwitterIcon" },
  { name: "LinkedinIcon" },
  { name: "ReadMoreIcon" },
  { name: "CloseSimpleIcon" },
];
